// Mock testimonials seed. The shape mirrors the `testimonials` table in
// docs/PRODUCT_BUILD_BLUEPRINT.md §10 (trimmed to fields the dashboard touches):
// a moderation `status`, `tags`, and the public/display fields a widget renders.
// The Inbox mutates this via the store; the Widget Studio renders only `approved`
// items. When a backend exists this fixture is swapped for real fetches.
export const sampleTestimonials = [
  {
    id: "t-ava",
    name: "Ava Marinänen",
    role: "Founder",
    company: "Linework",
    rating: 5,
    source: "x",
    status: "approved",
    tags: ["pricing page"],
    text: "We replaced three scattered tools with Halo in an afternoon. The widget on our pricing page looks like our designer built it by hand — it just matches.",
  },
  {
    id: "t-marcus",
    name: "Marcus Bell",
    role: "Head of Growth",
    company: "Northwind",
    rating: 5,
    source: "form",
    status: "approved",
    tags: ["growth"],
    text: "Collecting testimonials used to be a chore. Now I send one link, approve the good ones, and the wall updates itself. Conversion on the landing page is up noticeably.",
  },
  {
    id: "t-priya",
    name: "Priya Nair",
    role: "Course Creator",
    company: "The Calm Stack",
    rating: 5,
    source: "linkedin",
    status: "approved",
    tags: ["course", "design"],
    text: "The presets are the whole pitch for me. I picked Apple Glass, dropped in the embed, and my sales page suddenly felt premium without hiring anyone.",
  },
  {
    id: "t-sara",
    name: "Sara Lindqvist",
    role: "Agency Owner",
    company: "Studio Föhn",
    rating: 5,
    source: "google",
    status: "approved",
    tags: ["agency"],
    text: "I run testimonials for nine clients. Being able to theme each widget to match their brand — and preview it live — saves me hours every week.",
  },
  {
    id: "t-diego",
    name: "Diego Ferreira",
    role: "Indie Hacker",
    company: "",
    rating: 4,
    source: "form",
    status: "pending",
    tags: [],
    text: "Lightweight, fast, and the embed never broke a single deploy. That reliability alone is worth it for a solo founder shipping every day.",
  },
  {
    id: "t-tom",
    name: "Tom Okafor",
    role: "Product Lead",
    company: "Cadence",
    rating: 5,
    source: "x",
    status: "pending",
    tags: [],
    text: "The motion-first carousel is the first testimonial widget I've actually wanted on a page instead of tolerated. It feels native to the product.",
  },
  {
    id: "t-lena",
    name: "Lena Park",
    role: "Designer",
    company: "Foliage",
    rating: 5,
    source: "form",
    status: "pending",
    tags: [],
    text: "Halo's preset themes saved our launch. The Wall of Love page looked premium on day one, with zero design work from our side.",
  },
  {
    id: "t-spam",
    name: "growthhacker92",
    role: "",
    company: "",
    rating: 1,
    source: "form",
    status: "rejected",
    tags: [],
    text: "great tool!!! get 10k followers fast, check my profile and dm me for promo deals 🔥🔥",
  },
  {
    id: "t-legacy",
    name: "Ruth Adeyemi",
    role: "Marketing Lead",
    company: "Legacy Co",
    rating: 4,
    source: "manual",
    status: "archived",
    tags: ["2025 campaign"],
    text: "We used Halo for last year's launch campaign and the wall of testimonials carried the whole page. Still recommend it.",
  },
];

export const TESTIMONIAL_STATUSES = ["pending", "approved", "rejected", "archived"];
